export const SET_PROJECT = 'SET_PROJECT'

export const FETCH_TOPOLOGY_BEGIN = 'SET_TOPOLOGY_BEGIN'
export const FETCH_TOPOLOGY_SUCCESS = 'SET_TOPOLOGY_SUCCESS'
export const FETCH_TOPOLOGY_FAILURE = 'SET_TOPOLOGY_FAILURE'
